version: '3.7'
services:
  app:
    image: ricardo08/ajk-penugasan3:latest
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./tamiyochi-laravel/:/var/www
      - ./tamiyochi-laravel/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - rics-net

  webserver:
    image: nginx:stable-alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./tamiyochi-laravel/:/var/www
      - ./tamiyochi-laravel/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - rics-net

  db:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./tamiyochi-laravel/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - rics-net

networks:
  rics-net:
    driver: bridge

volumes:
  dbdata:
    driver: local
